# Generated by Django 4.1.7 on 2023-03-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_annoucement_meeting_delete_annoucements_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annoucement',
            new_name='Announcement',
        ),
    ]
